name: ğŸš€ Publish NPM Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write
      pull-requests: write

    steps:
      - name: ğŸ“¥ Checkout Code Repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: ğŸ“¦ Install Dependencies
        run: npm install

      - name: ğŸ› ï¸ Build Library
        run: npm run build-lib

      - name: ğŸ” Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: ğŸ” Check if Version Exists
        id: check-version
        run: |
          cd dist/quml-library
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          NPM_REGISTRY="https://registry.npmjs.org"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NPM_REGISTRY/$PACKAGE_NAME/$PACKAGE_VERSION")
          echo "status=$STATUS" >> $GITHUB_ENV

      - name: ğŸ•µï¸ Print NPM Token (for debugging purposes only)
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}"

      - name: ğŸš¢ Publish to NPM
        if: env.status != '200'
        run: |
          cd dist/quml-library
          if [[ "$(jq -r .version package.json)" == *"beta"* ]]; then
            npm publish --tag=beta --access public
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ğŸ“œ Log Version Exists
        if: env.status == '200'
        run: echo "Version already exists, skipping publish."
