name: ðŸš€ Publish NPM Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    environment: NPM_REGISTRY
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   id-token: write
    #   actions: write
    #   packages: write
    #   pull-requests: write

    steps:
      - name: ðŸ“¥ Checkout Code Repository
        uses: actions/checkout@v4

      - name: Verify creds1
        run: |
          echo ${{ vars.REPO_TESTVAR }}
          echo ${{ vars.TESTVAR }}
          echo ${{ vars.NPM_TOKEN }}
          # echo ${{ secrets.NPM_TOKEN }}
        env:
          REPO_TESTVAR: ${{ vars.REPO_TESTVAR }}
          TESTVAR: ${{ vars.TESTVAR }}
          NPM_TOKEN: ${{ vars.NPM_TOKEN }}

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: ðŸ“¦ Install Dependencies
        run: npm install

      - name: ðŸ› ï¸ Build Library
        run: npm run build-lib

      - name: ðŸ” Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: ðŸ” Check if Version Exists
        id: check-version
        run: |
          cd dist/quml-library
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          NPM_REGISTRY="https://registry.npmjs.org"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NPM_REGISTRY/$PACKAGE_NAME/$PACKAGE_VERSION")
          echo "status=$STATUS" >> $GITHUB_ENV

      - name: Verify creds
        run: |
          echo ${{ vars.NPM_TOKEN }}
          echo ${{ secrets.NPM_TOKEN }}
          echo $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ðŸš¢ Publish to NPM
        if: env.status != '200'
        run: |
          npm whoami
          cd dist/quml-library
          if [[ "$(jq -r .version package.json)" == *"beta"* ]]; then
            npm publish --tag=beta --access public
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ðŸ“œ Log Version Exists
        if: env.status == '200'
        run: echo "Version already exists, skipping publish."
