name: ðŸš€ Publish NPM Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write
      deployments: write
      discussions: write
      issues: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - name: ðŸ“¥ Checkout Code Repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ”‘ Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: ðŸ“¦ Install Dependencies
        run: npm install

      - name: ðŸ› ï¸ Build Library
        run: npm run build-lib

      - name: ðŸ” Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: ðŸ” Check if Version Exists
        id: check-version
        run: |
          cd dist/quml-library
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          NPM_REGISTRY="https://registry.npmjs.org"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NPM_REGISTRY/$PACKAGE_NAME/$PACKAGE_VERSION")
          echo "status=$STATUS" >> $GITHUB_ENV

      - name: ðŸš¢ Publish to NPM
        if: env.status != '200'
        run: |
          cd dist/quml-library
          if [[ "$(jq -r .version package.json)" == *"beta"* ]]; then
            npm publish --tag=beta --access public
          else
            npm publish --access public
          fi

      - name: ðŸ“œ Log Version Exists
        if: env.status == '200'
        run: echo "Version already exists, skipping publish."
