name: ğŸš€ Publish NPM Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write
      pull-requests: write

    steps:
      - name: ğŸ“¥ Checkout Code Repository
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: List files
        run: ls -la ~/

      - name: Create .npmrc
        run: |
          echo "@tekdi:registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Display .npmrc contents
        run: cat ~/.npmrc

      - name: ğŸ“¦ Install Dependencies
        run: npm ci

      - name: ğŸ› ï¸ Build Library
        run: npm run build-lib

      - name: List contents of dist/quml-library
        run: ls -la dist/quml-library

      - name: ğŸš¢ Publish to NPM
        run: |
          cd dist/quml-library
          pwd  # Print the current directory
          ls -la  # List the contents to ensure the package is present
          npm publish --tag=beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
