name: ðŸš€ Publish NPM Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write
      pull-requests: write

    steps:
      - name: ðŸ“¥ Checkout Code Repository
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ“¦ Install Dependencies
        run: npm ci

      - name: ðŸ› ï¸ Build Library
        run: npm run build-lib

      - name: ðŸ” Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: ðŸ” Check if Version Exists
        id: check-version
        run: |
          cd dist/quml-library
          pwd  # Print the current directory
          ls
          PACKAGE_NAME=$(jq -r .name package.json)
          echo "Package Name: $(jq -r .name package.json)"
          PACKAGE_VERSION=$(jq -r .version package.json)
          echo "Package Version: $(jq -r .version package.json)"
          NPM_REGISTRY="https://registry.npmjs.org"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$NPM_REGISTRY/$PACKAGE_NAME/$PACKAGE_VERSION")
          echo "status=$STATUS" >> $GITHUB_ENV

      - name: ðŸš¢ Publish to NPM
        echo env.status
        if: env.status != '200'
        run: |
          cd dist/quml-library
          pwd  # Print the current directory
          npm pack
          echo "-----------------------------------Package is packed---------------------------------------------"
          echo "-----------------------------------Contents inside directory-------------------------------------"
          ls
          if [[ "$(jq -r .version package.json)" == *"beta"* ]]; then
            echo "--- NPM Auth Check---"
            npm whoami
            echo "---Publish the package---"
            npm publish tekdi-sunbird-quml-player-* --tag=beta
          else
            npm publish tekdi-sunbird-quml-player-* --access public
          fi
        env:
          NODE_AUTH_TOKEN: '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'

      - name: ðŸ“œ Log Version Exists
        if: env.status == '200'
        run: echo "Version already exists, skipping publish."
